<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-03-28 19:47
=======
# Generated by Django 5.0.6 on 2024-05-23 18:49
>>>>>>> origin/master

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(max_length=500)),
<<<<<<< HEAD
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
=======
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('type', models.CharField(choices=[('personal', 'Personal'), ('work', 'Work'), ('study', 'Study')], default='personal ', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
>>>>>>> origin/master
            ],
        ),
    ]
